### ISSUE TITLE
Add localization system?

### ISSUE THREAD

**Issue by crafteverywhere** [Schmoller/Tubes#1]
I think you can consider the idea.I and many others can help you do the language files.

**Comment by Vexatos** [comment]
I would also love to have this. I would do the German translation.

**Comment by Schmoller** [comment]
This is now possible :D. I have added the en_US.lang file to assets/lang
https://github.com/Schmoller/Tubes/tree/liquid/assets/lang

Feel free to translate it if you wish. Just remember to keep it UTF-8

**Comment by Schmoller** [comment]
Ive updated the en_US lang file, would you two be interested in updating the translations? Thanks

**Comment by Schmoller** [comment]
Thanks a bunch
