### ISSUE TITLE
NPE when interacting with a GUI of a destroyed block.

### ISSUE THREAD

**Issue by fnuecke** [Schmoller/Tubes#22]
Version 2.0.4 for MC1.7.10. [Crashlog here](http://pastebin.com/dDtGBVir).

To reproduce, in multiplayer open the GUI of a requesting tube, then have another player break the block. After that, interacting with the GUI will crash the client. May apply to other tubes / inventories, too, didn't check.

The quick fix would probably be adding a null check in the corresponding places, a better one to close the GUI on the client when the block is destroyed (the tile entity's invalidate() should probably do).

**Comment by Schmoller** [comment]
Fixed
