### ISSUE TITLE
Compression tube rejects matching item stacks that are too large

### ISSUE THREAD

**Issue by fnuecke** [Schmoller/Tubes#23]
Not sure if this is a bug or by design, but it's certainly impractical: when a compression tube stores some items, and an item stack - of the same item type - that is too large to fit in arrives, it is rejected. I think it would be more appropriate to merge the items into a 64 stack that gets ejected, and keep the surplus in the compression tube?

To reproduce, have a chest with a requesting tube that leads into a compression tube that leads into another chest. Have the requesting tube pull a few single items, so they get stored in the compression tube. Then have the requesting tube pull a full 64 stack from the chest. That stack will continue to glitch between the pipe in front of the compression tube and the compression tube itself.

**Comment by Schmoller** [comment]
I'm not sure what caused it to happen for you, but it does not happen when I test this. It is already designed to let larger stacks pass through unhindered and when I tried with your specified setup, unfortunately I was unable to reproduce it.
