### ISSUE TITLE
crash with bc 6.1.5

### ISSUE THREAD

**Issue by nacno-toporiame** [Schmoller/Tubes#27]
it seems  that bc 6.1.5 has changed its way to add recipes to the refinery,that added an ID parameter the addRecipe FUnction
note:I can't fix
report:

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 11/5/14 7:00 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: buildcraft.core.recipes.RefineryRecipeManager.addRecipe(Lnet/minecraftforge/fluids/FluidStack;Lnet/minecraftforge/fluids/FluidStack;II)V
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:162)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:695)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:288)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:541)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:867)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: buildcraft.core.recipes.RefineryRecipeManager.addRecipe(Lnet/minecraftforge/fluids/FluidStack;Lnet/minecraftforge/fluids/FluidStack;II)V
    at schmoller.tubes.BuildcraftProxy.<init>(BuildcraftProxy.java:10)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at cpw.mods.fml.common.event.FMLPostInitializationEvent.buildSoftDependProxy(FMLPostInitializationEvent.java:40)
    at schmoller.tubes.ModTubes.postInit(ModTubes.java:141)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:694)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 273150496 bytes (260 MB) / 1020788736 bytes (973 MB) up to 1212153856 bytes (1156 MB)
    Mod Pack: Unknown / None
    LiteLoader Mods: 1 loaded mod(s)
          - VoxelMap version 1.2.3
    LaunchWrapper: 42 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: appeng.transformer.asm.ASMIntegration
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: cofh.asm.TransformerCore
          - Transformer: cofh.asm.PCCASMTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: codechicken.nei.asm.NEITransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: schmoller.tubes.asm.MinecraftTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: factorization.coremod.ASMTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: appeng.transformer.asm.ASMTweaker
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cofh.asm.PCCAccessTransformer
          - Transformer: factorization.coremod.FzAccessTransformer
          - Transformer: thaumic.tinkerer.preloader.AccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.JoinGamePacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerChatPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderCallbackInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LoginSuccessPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ServerCustomPayloadPacketTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.ChatPacketTransformer
          - Transformer: com.thevoxelbox.voxelmap.litemod.VoxelMapTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
    JVM Flags: 1 total; -Xmx1300m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.85.1232 Minecraft Forge 10.13.2.1232 Optifine OptiFine_1.7.10_HD_A4 106 mods loaded, 106 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    FML{7.10.85.1232} [Forge Mod Loader](forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Forge{10.13.2.1232} [Minecraft Forge](forge-1.7.10-10.13.2.1232.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    appliedenergistics2-core{rv1-stable-1} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    <CoFH ASM>{000} [CoFH ASM Data Initialization](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NotEnoughItems{1.0.3.64} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.64-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TubesCore{${version}} [Tubes Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Baubles{1.0.1.8} [Baubles](Baubles-1.7.10-1.0.1.8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Thaumcraft{4.2.1.4} [Thaumcraft](Thaumcraft-1.7.10-4.2.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    arsmagica2{1.4.0.005} [Ars Magica 2](1.7.10_AM2_1.4.0.005.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    bspkrsCore{6.13} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Treecapitator{1.7.2} [Treecapitator]([1.7.2]Treecapitator-universal-2.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    IC2{2.2.650-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.650-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AdvancedMachines{1.1.2} [IC2 Advanced Machines Addon](AdvancedMachinesAS-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels](AdvancedSolarPanel-1.7.10-3.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    appliedenergistics2{rv1-stable-1} [Applied Energistics 2](appliedenergistics2-rv1-stable-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BiblioCraft{1.8.2} [BiblioCraft](BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    CoFHCore{1.7.10R3.0.0B6} [CoFH Core](CoFHCore-[1.7.10]3.0.0B6-32.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Core{6.1.5} [BuildCraft](buildcraft-6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Forestry{3.1.1.4} [Forestry for Minecraft](forestry_1.7.10-3.1.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BiblioWoodsForestry{1.6} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.6].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ThermalFoundation{1.7.10R1.0.0B3} [Thermal Foundation](ThermalFoundation-[1.7.10]1.0.0B3-8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ThermalExpansion{1.7.10R4.0.0B5} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.0B5-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BigReactors{0.4.0rc9} [Big Reactors](BigReactors_0.4.0rc8.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Botania{r1.2-131} [Botania](Botania r1.2-131.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Builders{6.1.5} [BC Builders](buildcraft-6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Transport{6.1.5} [BC Transport](buildcraft-6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Silicon{6.1.5} [BC Silicon](buildcraft-6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Factory{6.1.5} [BC Factory](buildcraft-6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    BuildCraft|Energy{6.1.5} [BC Energy](buildcraft-6.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ChickenChunks{1.3.4.14} [ChickenChunks](ChickenChunks-1.7.10-1.3.4.14-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    chisel{1.5.7} [Chisel](Chisel-1.7.10-1.5.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Eln{43} [Electrical Age](ElectricalAge_BETA-1.9_r43.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded{1.7.10R2.8.0RC3} [MineFactory Reloaded](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Railcraft{9.3.3.0} [Railcraft](Railcraft_1.7.10-9.3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    EnderIO{1.7.10-2.1.7.254} [Ender IO](EnderIO-1.7.10-2.1.7.254.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    EE3{0.2.362} [Equivalent Exchange 3](EquivalentExchange3-1.7.10-0.2.362.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    exnihilo{1.37} [Ex Nihilo](Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    RedstoneArsenal{1.7.10R1.1.0B4} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.0B4-10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Waila{1.5.5} [Waila](Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    TConstruct{1.7.10-1.7.1.build771} [Tinkers' Construct](TConstruct-1.7.10-1.7.1c.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    exastris{For 1.7.10} [Ex Astris](Ex-Astris-1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    extracells{2.1.12} [ExtraCells](ExtraCells-1.7.10-2.1.12bnull.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ForgeMultipart{1.1.0.311} [Forge Multipart](ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ExtraUtilities{1.1.0k} [Extra Utilities](extrautilities-1.1.0k.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.10-0.8.88.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    factorization{1.7.10-0.8.88.2} [Factorization](Factorization-1.7.10-0.8.88.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    factorization.misc{1.7.10-0.8.88.2} [Factorization Miscellaneous Nonsense](Factorization-1.7.10-0.8.88.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    FastCraft{1.9} [FastCraft](fastcraft-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    McMultipart{1.1.0.311} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Mekanism{7.1.1} [Mekanism](Mekanism-1.7.10-7.1.1.122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MekanismGenerators{7.1.1} [MekanismGenerators](MekanismGenerators-1.7.10-7.1.1.122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MekanismTools{7.1.1} [MekanismTools](MekanismTools-1.7.10-7.1.1.122.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ResonantEngine{@MAJOR@.@MINOR@.@REVIS@} [Resonant Engine](resonant-engine-2.2.0.172-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MFFS{@MAJOR@.@MINOR@.@REVIS@} [Modular Force Field System](mffs-4.1.0.38-core.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    minechem{5.0.5.229} [Minechem](Minechem-1.7.10-5.0.5.229.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0RC3} [MFR Compat: Applied Energistics](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatAtum{1.7.10R2.8.0RC2} [MFR Compat: Atum](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0RC3} [MFR Compat: BackTools](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0RC3} [MFR Compat: BuildCraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0RC2} [MFR Compat: Chococraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0RC2} [MFR Compat: ExtraBiomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatForestry{1.7.10R2.8.0RC3} [MFR Compat: Forestry](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0RC3} [MFR Compat: ForgeMicroblock](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatIC2{1.7.10R2.8.0RC3} [MFR Compat: IC2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0RC2} [MFR Compat: Mystcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatPams{1.7.10R2.8.0RC2} [MFR Compat: Pam's Mods](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjRed|Core{4.5.1.51} [ProjectRed](ProjectRed-Base-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjRed|Exploration{4.5.1.51} [ProjectRed-Exploration](ProjectRed-World-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0RC2} [MFR Compat ProjectRed](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0RC3} [MFR Compat: Railcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatRP2{1.7.10R2.8.0RC2} [MFR Compat: RP2](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0RC2} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0RC3} [MFR Compat: Thaumcraft](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0RC3} [MFR Compat: Thermal Expansion](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0RC3} [MFR Compat: TwilightForest](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0RC3} [MFR Compat: Vanilla](MineFactoryReloaded-[1.7.10]2.8.0RC3-591.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9B.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ModTweaker{0.6} [ModTweaker](ModTweaker-1.7.X-0.6-0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NBTEdit{1.7.2.2} [In-game NBTEdit](NBTEdit_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NEIAddons{1.12.2.9} [NEI Addons](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NEIAddons|Botany{1.12.2.9} [NEI Addons: Botany](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NEIAddons|Forestry{1.12.2.9} [NEI Addons: Forestry](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NEIAddons|CraftingTables{1.12.2.9} [NEI Addons: Crafting Tables](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NEIAddons|ExNihilo{1.12.2.9} [NEI Addons: Ex Nihilo](neiaddons-mc1710-1.12.2.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NEIPlugins{1.1.0.11-unofficial} [NEI Plugins Unofficial](NEIPlugins-MC1.7.10-1.1.0.11-unofficial.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    NetherOres{1.7.10R2.3.0RC3} [Nether Ores](NetherOres-[1.7.10]2.3.0RC3-84.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjRed|Transmission{4.5.1.51} [ProjectRed-Transmission](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjRed|Transportation{4.5.1.51} [ProjectRed-Transportation](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjRed|Compatibility{4.5.1.51} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjRed|Integration{4.5.1.51} [ProjectRed-Integration](ProjectRed-Integration-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjRed|Illumination{4.5.1.51} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ProjRed|Expansion{4.5.1.51} [ProjectRed-Expansion](ProjectRed-Mechanical_beta-1.7.10-4.5.1.51.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    thaumicenergistics{0.7.2b} [Thaumic Energistics](thaumicenergistics-0.7.2b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ThaumicTinkerer{2.5-1.7.10-158} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-158.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Translocator{1.1.1.13} [Translocator](Translocator-1.7.10-1.1.1.13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    Tubes{2.0.4} [Tubes](Tubes-1.7.10-2.0.4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Errored
    WR-CBE|Core{1.4.1.7} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    WR-CBE|Addons{1.4.1.7} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    WR-CBE|Logic{1.4.1.7} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.7-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    aobd{2.2.5} [Another One Bites The Dust](AOBD-2.2.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    ForgeMicroblock{1.1.0.311} [Forge Microblocks](ForgeMultipart-1.7.10-1.1.0.311-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized
    AE2 Version: stable rv1-stable-1 for Forge 10.13.0.1187
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    TConstruct Environment: Environment healthy.
    Forestry : [Forestry] Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, MJ6:ON, MJ5:ON, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:ON, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:ON, ImmibisMicroblocks:OFF, BetterStorage:OFF

**Comment by Schmoller** [comment]
Fixed

**Comment by nacno-toporiame** [comment]
published?

**Comment by Schmoller** [comment]
Ive pushed the update to Curseforge, it will hopefully be up soon
