### ISSUE TITLE
Integrate ChickenBones DepLoader

### ISSUE THREAD

**Issue by psychofad** [Schmoller/Tubes#3]
Would be great if you could integrate the DepLoader into your mod as I use other mods that have this and it will automatically download the ForgeMultiPart.  Assuming this would be ok for your mod I added it but it does it's check for the dependancies before the DepLoader has a chance to grab the MultiPart files requiring me to manually add them each time I update my modpack which is an un-needed PITA after hours of sifting through configs and whatnot.  

Love the mod BTW.  Don't mean to be a basher, but if you could throw in the DepLoader that would save a lot of issues for modpack authors.

DepLoader code (may be outdated but its what i could find)
https://bitbucket.org/ChickenBones/codechickencore/src/1c4bcdbbfcf60863c1631761eb2717e9f9a6b5ec/codechicken/core/launch/DepLoader.java

ChickenBones may even lend you a hand getting things set up proper...he's got his hands everywhere I see lately :P

**Comment by Schmoller** [comment]
Going to close this because it doesnt allow version selecting based on mcversion meaning I would have to have 2 downloads for tubes instead of 1
