### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Zyles** [Schmoller/Tubes#9]
Recently updated some OTHER mods and this is what happens when I start now:
http://pastebin.com/pVxzEmjT

Why would it start crashing?

I can "fix" it, by removing tubes mod from the mods dir, running MC once, and then adding it back. Then it boots. But I can't tell my users to do that.

Maybe you are doing some weird id-conflicting things.

**Comment by Schmoller** [comment]
Actually I have seen this a few times before and I have no idea what happens. Usually you don't actually need to remove it, just restarting MC is enough. 

May I ask what mods you updated? I have never been able to track down what caused this so that may offer some clues.

**Comment by Zyles** [comment]
Yeah running it again seems to work.

What is weird however. I distribute the modpack via technic launcher. And EVERY first run on a new install it crashes.

**Comment by copygirl** [comment]
Looking at the forge log would be useful for checking the loading order of the mods. This seems really weird.

**Comment by Schmoller** [comment]
Good idea copygirl, Zyles do you have the ForgeModLoader-client-_number_.log file from when the crash occured? And If so could you show me please.

**Comment by Zyles** [comment]
Here is first boot:

http://pastebin.com/UgkmEgrN

**Comment by copygirl** [comment]
Seems to me that there's an issue with FML because it's not loading ForgeMultipart before Tubes, even though it's "required-before".

**Comment by Schmoller** [comment]
No actually required-before puts tubes before FMP which is normal, but its not usually a problem because the classloader for fmp is created during an earlier stage.

However I see that multipart was downloaded during load and I'm wondering if somehow that upset fml. I'll have to do more testing

**Comment by Schmoller** [comment]
Ok there we go, just tried it. When it has to download FMP, tubes will crash. I'll try to find out why

**Comment by Schmoller** [comment]
Fixed, will be in next version
